- name: Read version string from iso packages
  shell: cat {{ vyos_install_root }}/opt/vyatta/etc/version | awk '{print $2}' | tr + -
  register: result

- name: Set vyos_version
  set_fact:
    vyos_version: "{{ result.stdout }}"

- name: Set VyOS release name equuleus
  set_fact:
    vyos_debian_codename: "bullseye"
    vyos_release: "equuleus"
  when: vyos_version is regex("^1\.3.*$")

- name: Set VyOS release name sagitta
  set_fact:
    vyos_debian_codename: "bookworm"
    vyos_release: "sagitta"
  when: vyos_version is regex("^1\.4.*$")

- name: Set VyOS debian code name equuleus
  set_fact:
    vyos_debian_codename: "bookworm"
    vyos_release: "current"
  when: vyos_version is regex("^1\.5.*$") or vyos_version is regex("^current$")
