name: tailscale-1.3.5
vyos_target:
  # This is used to target an appropriate vyos-core version when using modules
  # that patch the core
  branch: 1.3.5
  release: equuleus
  # This is the name of an iso found under resources/isos
  iso: vyos-1.3.5-amd64.iso
modules:
  - type: git
    url: https://github.com/jack-broadway/vyos-module-tailscale.git
    version: main
