---
- name: copy iso files
  become: true
  synchronize:
    src: "{{ vyos_cd_root }}/"
    dest: "/tmp/live-{{ vyos_version }}"

- name: Delete filesystem.squashfs
  become: true
  file:
    path: "/tmp/live-{{ vyos_version }}/live/filesystem.squashfs"
    state: absent

- name: compress path to squashfs image
  become: true
  command: mksquashfs {{ vyos_install_root }} /tmp/live-{{ vyos_version }}/live/filesystem.squashfs -comp xz

- name: Get md5 sum of squashfs
  stat:
    path: "/tmp/live-{{ vyos_version }}/live/filesystem.squashfs"
    checksum_algorithm: md5
    get_checksum: yes
  register: squashfs_stat_md5

- name: Update iso MD5
  ansible.builtin.lineinfile:
    path: "/tmp/live-{{ vyos_version }}/md5sum.txt"
    search_string: "./live/filesystem.squashfs"
    line: "{{ squashfs_stat_md5.stat.checksum}}  ./live/filesystem.squashfs"

- name: Get sha256 sum of squashfs
  stat:
    path: "/tmp/live-{{ vyos_version }}/live/filesystem.squashfs"
    checksum_algorithm: sha256
    get_checksum: yes
  register: squashfs_stat_sha256

- name: Update iso SHA256
  ansible.builtin.lineinfile:
    path: "/tmp/live-{{ vyos_version }}/sha256sum.txt"
    search_string: "./live/filesystem.squashfs"
    line: "{{ squashfs_stat_sha256.stat.checksum}}  ./live/filesystem.squashfs"

- name: Verify MD5 checksums of all the files in the new ISO image
  command: md5sum -c md5sum.txt
  args:
    chdir: "/tmp/live-{{ vyos_version }}"
  changed_when: False

- name: Verify SHA256 checksums of all the files in the new ISO image
  command: sha256sum -c sha256sum.txt
  args:
    chdir: "/tmp/live-{{ vyos_version }}"
  changed_when: False

- name: create new iso
  become: true
  command:  > 
    xorriso -as mkisofs -R -r -J -joliet-long -l -cache-inodes \
    -iso-level 3 -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -partition_offset 16 -A "VyOS" -p "live-build 1:20190311.1; \
    https://debian-live.alioth.debian.org/live-build" \
    -publisher "autobuild@vyos.net" -V "VyOS" --modification-date={{ lookup('pipe','date +\"%Y%m%d%H%M%S%2N\"') }} \
    -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 \
    -boot-info-table -eltorito-alt-boot  -e boot/grub/efi.img -no-emul-boot \
    -isohybrid-gpt-basdat -isohybrid-apm-hfsplus -o /ansible/vyos-custom.iso /tmp/live-{{ vyos_version }}